Traceback (most recent call last):
  File "/home/estebanbecerraf/scripts/train/entrenamiento_vgg16_gpu.py", line 12, in <module>
    with open("home/estebanbecerraf/config/config_gpubase.yaml", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'home/estebanbecerraf/config/config_gpubase.yaml'
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/opt/conda/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1199, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.12/site-packages/accelerate/commands/launch.py", line 778, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '/home/estebanbecerraf/scripts/train/entrenamiento_vgg16_gpu.py']' returned non-zero exit status 1.
